# Generated by Django 3.1.1 on 2020-09-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200910_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.TextField(null=True),
        ),
    ]
